export const errorMessages = {
  TAG_IS_ALREADY_EXIST: 'error: Tag already exist',
  TAG_NOT_FOUND: 'error: Tag not found',
  POST_NOT_FOUND: 'error: Post not found',
  USER_ALREADY_EXISTS: 'error: user Already Exists',
  INCORRECT_CREDENTIALS: 'error: incorrect Credentials',
  MSG_ALREADY_SENT: 'error: message Already Sent',
  INVALID_SMS_CODE: 'error: invalid SMS Code',
  USER_NOT_FOUND: 'error: user Not Found',
  NOT_EXIST: 'error: not Exist',
  TOKEN_EXPIRED: 'error: token Expired',
  WRONG_EMAIL: 'error: wrong Email',
  NOT_ORDERS: 'error: no Orders',
  INCORRECT_ARRAY: 'error: order request must be an array',
  EMPTY_ARRAY: 'error:empty array',
  INCORRECT_REQUEST: 'error:Bad Request',
  TOKEN_NOT_EXIST: 'error: Token not exist',
  SOMETHING_WENT_WRONG: 'error: Something went wrong',
  COMMENT_NOT_FOUND: 'error: Comment not found',
};
